version: "3"

services:
    db:
        image: postgres
        ports:
            - "5432:5432"
    descomplicaback:
        build: .
        command: npm start
        ports: 
            - "4000:4000"
        depends_on:
            - "db"
        volumes:
            - .:/app